name = "ConstraintProgrammingExtensions"
uuid = "b65d079e-ed98-51d9-b0db-edee61a5c5f8"
authors = ["Thibaut Cuvelier"]
version = "0.5.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MathOptInterface = "~0.9"
julia = "^1"
